services:

  db:
    image: mysql:8.0
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: